# location: eastus1

# see https://docs.microsoft.com/en-us/azure/openshift/support-policies-v4#supported-virtual-machine-sizes
vmSize: Standard_D4s_v3

# zones: ['1','2','3']
zoneCount: 2
replicasPerZone: 1

# default will create infra nodes
machineRole: "infra"

machineLabels:
  node-role.kubernetes.io/infra: ""

machineTaints:
  - key: node-role.kubernetes.io/infra
    effect: NoSchedule

## Ignore these unless using `helm template` as they're auto-discovered.
clusterSpec:
  infraId: bifrost-cluster-9zps5
  location: northeurope

machineSetSpec:
  image:
    offer: aro4
    publisher: azureopenshift
    resourceID: ""
    sku: aro_410
    version: 410.84.20220125
  location: northeurope
  networkResourceGroup: bifrost-aro
  osDisk:
    diskSettings: {}
    diskSizeGB: 128
    managedDisk:
      storageAccountType: Premium_LRS
    osType: Linux
  publicIP: false
  publicLoadBalancer: bifrost-cluster-9zps5
  resourceGroup: aro-izvqz38w
  subnet: bifrost-cluster-aro-worker-subnet
  vnet: bifrost-cluster-aro-vnet